dist: bionic

matrix:
  include:
    - os: osx

language: c


install:
  - git clone https://github.com/tj/git-extras
  - cd git-extras && make

script:
  - git info
  - git submodule status | sed 's/\([^abcdef0-9]\{0,2\}\)\([abcdef0-9]\{7\}\)\([abcdef0-9]\{33\}\)\(.*\)/\1\2\4/'
