dist: bionic

matrix:
  include:
    - os: osx

language: c


script:
  - git clone https://github.com/spacewander/git-extras.git -b utimes && cd git-extras
  - touch $(git ls-files | xargs)
  - ls -l $(git ls-files | xargs)
  - make && git utimes
  - ls -l $(git ls-files | xargs)
