dist: bionic

matrix:
  include:
    - os: osx

language: c


script:
  - git clone https://github.com/tj/git-extras.git && cd git-extras
  - touch $(git ls-files | xargs)
  - ls -l $(git ls-files | xargs)
  - ./bin/git-utimes
  - ls -l $(git ls-files | xargs)
