version: 0.0.1.{build}-test
shallow_clone: true
matrix:
  fast_finish: true

platform:
  - x64
  - x86

install:
  - echo "install"

build_script:
  - clang -std=c89 -Wpedantic sizeof.c -g -o test.exe

test_script:
  - .\test.exe