name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-18.04
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out code.
        uses: actions/checkout@v2
      - name: Linux Install
        if: matrix.platform == 'ubuntu-18.04'
        run: |
          sudo apt-get install -y bsdmainutils
      - name: Script
        run: |
          git clone https://github.com/tj/git-extras.git && cd git-extras
          sudo make
          #sudo ./t.sh

  report-success:
    runs-on: ubuntu-latest
    needs: build
    name: Set commit status to success
    if: ${{ success() }}
    steps:
    - uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f # v1.1.6
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.vars.outputs.sha }}
        context: ${{ github.workflow }}
        description: Datapath BPF Complexity tests successful
        state: success
        target_url: ${{ env.check_url }}

  report-failure:
    runs-on: ubuntu-latest
    needs: build
    name: Set commit status to failure
    if: ${{ failure() }}
    steps:
    - uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f # v1.1.6
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.vars.outputs.sha }}
        context: ${{ github.workflow }}
        description: Datapath BPF Complexity tests failed
        state: failure
        target_url: ${{ env.check_url }}

  report-cancelled:
    runs-on: ubuntu-latest
    needs: build
    name: Set commit status to cancelled
    if: ${{ cancelled() }}
    steps:
    - uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f # v1.1.6
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ steps.vars.outputs.sha }}
        context: ${{ github.workflow }}
        description: Datapath BPF Complexity tests cancelled
        state: error
        target_url: ${{ env.check_url }}
