name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-18.04
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out code.
        uses: actions/checkout@v2
      - name: Linux Install
        if: matrix.platform == 'ubuntu-18.04'
        run: |
          sudo apt-get install -y bsdmainutils
      - name: Script
        run: |
          git clone https://github.com/tj/git-extras.git && cd git-extras
          sudo make
          sudo ./t.sh
