name: ci
on:
  push:
    branches: [ "ci/**" ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-18.04
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out code.
        uses: actions/checkout@v2
      - name: Linux Install
        if: matrix.platform == 'ubuntu-18.04'
        run: |
          sudo apt-get install -y bsdmainutils
      - name: Script
        run: |
          git clone https://github.com/tj/git-extras.git && cd git-extras
          sudo make
          mv ../t.sh t.sh
          sudo ./t.sh
      - name: Bump version
        if: matrix.platform == 'macos-latest'
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{secrets.BREW_TOKEN}}
          formula: git-extras
          tag: 6.3.0
          revision: 0c0be924459c68aac9f2cf1acadb302dad1c64f6
